# Generated by Django 6.1 on 2026-08-25 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire', models.DateTimeField()),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='formation.formateur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='formation.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formation.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formation.session')),
            ],
        ),
    ]
